apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-config
  namespace: {{ .Release.Namespace | default "fitness" }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  PORT: {{ .Values.config.PORT | quote }}
