{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-pvc
  namespace: {{ .Release.Namespace | default "fitness" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}
