apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fitness-tracker.fullname" . }}-secret
  namespace: {{ .Release.Namespace | default "fitness" }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secret.MONGODB_URI | quote }}
